version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__GRACEFUL_SHUTDOWN: "true"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-seeker-api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app # 코드 변경 즉시 반영
      - ./requirements.txt:/app/requirements.txt
      - model_cache:/root/.cache/torch/sentence_transformers/ # 모델 캐시 유지
      # - model_data:/app/models # 모델 데이터를 영구 저장할 볼륨 (로컬 마운트로 대체)
      - logs_data:/app/logs # 로그 데이터도 영구 저장
      # 로컬에 다운로드한 모델 디렉토리 마운트
      - ./models:/app/models
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OMP_NUM_THREADS=1
      - PYTHONUNBUFFERED=1

volumes:
  qdrant_data:
  model_cache: # 모델 캐시용 볼륨 추가
  model_data: # 영구적인 모델 데이터 볼륨
  logs_data: # 영구적인 로그 데이터 볼륨
