version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__GRACEFUL_SHUTDOWN: "true"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-seeker-api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt
      - ./models:/code/models
      - ./logs:/code/logs
      - ./.cache:/root/.cache
    environment:
      - QDRANT_URL=http://qdrant:6333
      - MODEL_PATH=/code/models/gguf/polyglot-ko-1.3b.gguf
      - LOG_LEVEL=INFO
      - OMP_NUM_THREADS=1
    restart: unless-stopped

volumes:
  qdrant-data:
