version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # 호스트 6333 → 컨테이너 6333
    environment:
      QDRANT__SERVICE__GRACEFUL_SHUTDOWN: "true"
    volumes:
      - qdrant_data:/qdrant/storage # 벡터 데이터 영속화

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-seeker-api
    depends_on:
      - qdrant
    ports:
      - "8000:8000" # 호스트 8000 → 컨테이너 8000
    volumes:
      - ./app:/app/app # 코드 변경 즉시 반영 (개발용)
      - ./requirements.txt:/app/requirements.txt
    environment:
      - QDRANT_URL=http://qdrant:6333

volumes:
  qdrant_data:
